services:
  tuvino:
    restart: always
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    #deploy:
    #  resources:
    #    reservations:
    #      memory: 256M
