services:
  tuvino:
    restart: always
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - SUPABASE_URL
      - SUPABASE_KEY
    deploy:
      resources:
        reservations:
          memory: 256M
